#include <stdio.h>
#include <stdlib.h>

#include "tree.h"


int main()
{
    FILE* in;
    in=fopen("input.txt","r");
    if (in==NULL)
    {
        printf("Cannot open file!");
        getch();
        return -1;
    }


    NodeT *root=(NodeT*)malloc(sizeof(NodeT*));

    //root = createBinTree(in);  // Construct binary tree from a .txt file

    root = createAVL_BST(in); // Order doesn't matter - automatically generated

    printf("Tree generated by input.txt:\n\n");
    prettyPrint(root,0);  // Print the tree

    int data;

    printf("\nData to insert: ");
    scanf("%d",&data);
    insert_balanced(&root, data);
    printf("\nTree after balancing:\n");
    prettyPrint(root,0);  // Print the new tree
/*
    printf("\nData to delete: ");
    scanf("%d",&data);
    delete_balanced(root, data);
    printf("\nTree after deleting element:\n");
    prettyPrint(root,0);  // Print the new tree
*/
    getch();
    return 0;
}
