#include "tree.h"



int main()
{
    FILE* in;
    in=fopen("input.txt","r");
    NodeT *root = createBinTree(in);  // Construct binary tree from a .txt file (this makes it easier to run the program)

    printf("Tree generated by input.txt:\n\n");
    prettyPrint(root,0);  // Print the tree

    NodeL *list = getListFromTree(root); // Construct DLList from the binary tree
    printf("\nList generated by the tree:\n");
    printList(list);  // Print the list (it should be the same as in the input .txt)

    root = getTreeFromList(&list);  // Reconstruct the tree from the List
    printf("\nTree generated by list (it should be identical to the first one):\n\n");
    prettyPrint(root,0);  // Print out the tree (it should be the same as the input tree)

    fclose(in);
    return 0;
}
