void addFirst(int x);
void addLast(int x);
void deleteFirst();
void deleteLast();
void deleteElementX(int x);
void printAll();
void printFirstX(FILE* g,int x);
void printLastX(FILE *g,int x);
void doomTheList();
void initializeList();
